--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: decrypt_aes(text, text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.decrypt_aes(encrypted_data text, secret text) RETURNS text
    LANGUAGE plpgsql
    AS $$
DECLARE
    key BYTEA = decode(secret, 'escape');
BEGIN
    IF encrypted_data = '' THEN
        RETURN encrypted_data;
    ELSE
        RETURN convert_from(decrypt(decode(encrypted_data, 'base64'), key, 'aes-ecb/pad:pkcs'), 'UTF8');
    END IF;
END;
$$;


ALTER FUNCTION public.decrypt_aes(encrypted_data text, secret text) OWNER TO postgres;

--
-- Name: encrypt_aes(text, text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.encrypt_aes(data text, secret text) RETURNS text
    LANGUAGE plpgsql
    AS $$
DECLARE
    key BYTEA = decode(secret, 'escape');
BEGIN
    IF data = '' THEN
        RETURN data;
    ELSE
        RETURN replace(encode(encrypt(data::bytea, key, 'aes-ecb/pad:pkcs'), 'base64'), E'\n', '');
    END IF;
END;
$$;


ALTER FUNCTION public.encrypt_aes(data text, secret text) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.person OWNER TO postgres;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    address character varying(255),
    email character varying(255),
    name character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (id, name) FROM stdin;
1	kSlQa+WtMUg5C9zZJHPOMTukMTdSAl0p1KVvonIu4A+MkSiAKM8frpi8Qb8laB8Vv4VBIN+skM4mFTIICNqEcvRHDprDPC495bmkxbq1DoCt99GKqh1Qf0I1nasd3ZeuxAdM/Soq5kFvE2VjLKT8CYiH6UkbeNpfW9bMgUe3XS4=
2	zMM6MYR4Bvdh5x8iNIFIVw==
6	bLmsLO2kT8dK7rvzd93IqQ==
7	bLmsLO2kT8dK7rvzd93IqQ==
8	PdoB+xh9DjB6Wh3zR7qExw==
9	DzH+YzTfEcEF43193w2MP9+4fLTgzDlU7hQD17M8Fko=
11	fhVsMy+augn6TNS6eWuXVK6OHHmMPPu7WbTR0ZEFQH6dnsZKgZeNSU1IgT2xNB8D
12	ugsfSAHzWbJcVSvZKfnm8g==
13	BekVLwfEm3oA3kVKxdBDfsqgb6WX+siKpR6hbTTGZujdfRs+fu4nFV3nyW1YUKIf67PK2lugwTPkmJLsBX+2QQ==
14	bywTOtNPLj9Iq4ugxruR1Q==
19	gdHD3rLKMQfR9NFaFF+AKocicGqZqiHuMd6h28yLmnUOYLYDDml1aJIFcI5MZc0X7FXQTIJ8ywpvW+9e7BLeqlXyRRnzsxhpEdBtmGL0ozMxer5A/AVah/jY8ACPecEa
28	Ey5gIoCEQaB0tf+p2pNLgaa0idL7r0anvHv/1UnVbawQf4p+qXpIFzoZI3laXQQ7ywyekZluOUi94xDnps9EDkfkMFi3uL/Bg5+K2J2ckoiD9Iv0p6o1fvb+lEIYmgmJNUW9zBBmD7jZZlyQ+SBGGBYmWcrt/XF9AYNA70kzDPY=
27	VV+69UADQknDeQpZJ37HrM2FhblJl+Rnpvwpl0mYsxAWwm79SD0F2+nLAu+SyDGu/bxPH5GxXY+lROeNqZ2vFw==
30	Ey5gIoCEQaB0tf+p2pNLgaa0idL7r0anvHv/1UnVbawQf4p+qXpIFzoZI3laXQQ7ywyekZluOUi94xDnps9EDkfkMFi3uL/Bg5+K2J2ckoiD9Iv0p6o1fvb+lEIYmgmJ59SHeE5cQcBlRM0DR7HW8GkgB3ZVcuet+ZtW4RzgfOQ=
31	Ey5gIoCEQaB0tf+p2pNLgaa0idL7r0anvHv/1UnVbawQf4p+qXpIFzoZI3laXQQ7ywyekZluOUi94xDnps9EDkfkMFi3uL/Bg5+K2J2ckoiD9Iv0p6o1fvb+lEIYmgmJ59SHeE5cQcBlRM0DR7HW8GkgB3ZVcuet+ZtW4RzgfOQ=
32	iIfpSRt42l9b1syBR7ddLg==
33	\N
34	
35	
25	oaQdgR/ojcG0FmtPDwLWDf8xQNbK+Ey0zyCi3ib6JNvVxJHr+zgGx1i4TsP7l2jcRN6ZN8i5C5SV0sbXbs2YkrK9ndvYo4+6Uey7mmBrx7g=
26	oaQdgR/ojcG0FmtPDwLWDY2O2FcmemJt9GmShupapotY2Rl0kugn14ZZqWMY4YedrKdyV86eluWhi+2PyLRU5tvvmUHWOQwN3LclWU6kSUc=
29	Ey5gIoCEQaB0tf+p2pNLgaa0idL7r0anvHv/1UnVbawQf4p+qXpIFzoZI3laXQQ7ywyekZluOUi94xDnps9EDkfkMFi3uL/Bg5+K2J2ckoiD9Iv0p6o1fvb+lEIYmgmJNUW9zBBmD7jZZlyQ+SBGGBYmWcrt/XF9AYNA70kzDPY=
24	gdHD3rLKMQfR9NFaFF+AKnXOdu50VfOLD1nSY8fg6Ur6MzudvtV7dzc/rF+ClefnIG/l4mcEGFu50xSYE82N1kq5DgFjHwlwG9IdQmb7dVw=
36	32nSVKxSGKRUS07agLpQHA==
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, address, email, name) FROM stdin;
1	Nardipur	aditya@gmail.com	tOgG0rk097CGjhXZhbCIDg==
3	Nardipur	aditya@gmail.com	a4TuvxRGt4u9tzj9SDcSifi3By5d+7XQIuiGKt/IXt4=
4	ahmedabad	test@gmail.com	m2eTC9MOlLl83DaWPCgEi+Ru1yxGNzwGKwdbATmeh30=
5	ahmedabad	test@gmail.com	kSlQa+WtMUg5C9zZJHPOMTukMTdSAl0p1KVvonIu4A+MkSiAKM8frpi8Qb8laB8Vv4VBIN+skM4mFTIICNqEcvRHDprDPC495bmkxbq1DoCt99GKqh1Qf0I1nasd3ZeuxAdM/Soq5kFvE2VjLKT8CYiH6UkbeNpfW9bMgUe3XS4=
6	ahmedabad	test@gmail.com	kSlQa+WtMUg5C9zZJHPOMTukMTdSAl0p1KVvonIu4A+MkSiAKM8frpi8Qb8laB8Vv4VBIN+skM4mFTIICNqEchXSXeDxysM3K+jOUF/ONeC/wSp0RtkhMs+g0FqRTbIk2vI62BCCPn9DiT4/7Iyz9URJUYLBuLyOOlnkjmB2hDI=
7	ygui	test@mail.com	PdoB+xh9DjB6Wh3zR7qExw==
8	gandhinagar	demo@gmail.com	kSlQa+WtMUg5C9zZJHPOMTukMTdSAl0p1KVvonIu4A+MkSiAKM8frpi8Qb8laB8Vv4VBIN+skM4mFTIICNqEchXSXeDxysM3K+jOUF/ONeC/wSp0RtkhMs+g0FqRTbIk2vI62BCCPn9DiT4/7Iyz9URJUYLBuLyOOlnkjmB2hDI=
9	\N	test@mail.com	kSlQa+WtMUg5C9zZJHPOMbtLqJqm6YuNKyXFRW48TS0ca8uOPHiyMhJi0rn9gNn+bKIneoK9kahK\nmCESyI0PqSEi4PbC4nOBHWgAVnhHCPbewCa+mZDaE3OksJ2N7SU8i+Id9JvjQnjKr9UlitnAeS1g\n/BFBEjzWUZhP8vh/sCM=
\.


--
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 36, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 9, true);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

